version: "3.5"
services:
  ros_fastdds_discovery_server:
    image: rob750:latest
    network_mode: host
    ipc: host
    restart: unless-stopped
    # Launch the FastDDS discovery sever to bypass the need of multicast to discover nodes
    command: fastdds discovery -i 0 -p 21000
  spot_ros2:
    image: rob750:latest
    network_mode: host
    ipc: host
    restart: unless-stopped
    volumes:
      # Mount payload credentials.
      # - /opt/payload_credentials/payload_guid_and_secret:/opt/payload_credentials/payload_guid_and_secret
      - $PWD/source:/home/workspaces
    environment:
      - SPOT_IP=192.168.50.3   
      - ROS_DOMAIN_ID=56       
      - ROS_DISCOVERY_SERVER=192.168.80.3:21000   
      # - PAYLOAD_CREDENTIALS=/opt/payload_credentials/payload_guid_and_secret
    # Launch the Spot ROS 2 driver 
    # command: ros2 launch spot_driver spot_driver.launch.py config_file:=/spot_ros_params.yml
    depends_on:
      - ros_fastdds_discovery_server